# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/users/kakizaki/graduate_report/design_code/vivado/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/users/kakizaki/graduate_report/design_code/vivado/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/users/kakizaki/graduate_report/design_code/vivado/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/users/kakizaki/graduate_report/design_code/src/AT93C46_IIC.v
  /home/users/kakizaki/graduate_report/design_code/src/BRAM128_9B9B.v
  /home/users/kakizaki/graduate_report/design_code/src/IIC_CORE.v
  /home/users/kakizaki/graduate_report/design_code/src/IIC_CTL.v
  /home/users/kakizaki/graduate_report/design_code/src/Led.v
  /home/users/kakizaki/graduate_report/design_code/src/PCA9548_SW.v
  /home/users/kakizaki/graduate_report/design_code/src/SiTCP_XC7K_32K_BBT_V110.v
  /home/users/kakizaki/graduate_report/design_code/src/TIMER.v
  /home/users/kakizaki/graduate_report/design_code/src/Transport.v
  /home/users/kakizaki/graduate_report/design_code/src/WRAP_SiTCP_GMII_XC7K_32K.v
  /home/users/kakizaki/graduate_report/design_code/src/kc705sitcp.v
}
read_edif /home/users/kakizaki/graduate_report/design_code/ngc/SiTCP_XC7K_32K_BBT_V110.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/users/kakizaki/graduate_report/design_code/xdc/SiTCP.xdc
set_property used_in_implementation false [get_files /home/users/kakizaki/graduate_report/design_code/xdc/SiTCP.xdc]

read_xdc /home/users/kakizaki/graduate_report/design_code/xdc/kc705sitcp.xdc
set_property used_in_implementation false [get_files /home/users/kakizaki/graduate_report/design_code/xdc/kc705sitcp.xdc]


synth_design -top kc705sitcp -part xc7k325tffg900-2


write_checkpoint -force -noxdef kc705sitcp.dcp

catch { report_utilization -file kc705sitcp_utilization_synth.rpt -pb kc705sitcp_utilization_synth.pb }
